// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Safe identification entity types
type EntityType int32

const (
	EntityType_UNKNOWN  EntityType = 0
	EntityType_PRODUCER EntityType = 1
	EntityType_DBNODE   EntityType = 2
	EntityType_CONSUMER EntityType = 3
	EntityType_BANK     EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PRODUCER",
		2: "DBNODE",
		3: "CONSUMER",
		4: "BANK",
	}
	EntityType_value = map[string]int32{
		"UNKNOWN":  0,
		"PRODUCER": 1,
		"DBNODE":   2,
		"CONSUMER": 3,
		"BANK":     4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // e.g., "DataClub", "DB1", "ClienteA", "BancoUSM"
	EntityType    EntityType             `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=proto.EntityType" json:"entity_type,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // IP:Port of the entity (if server)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RegisterRequest) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_UNKNOWN
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Event structure
type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // uuidv4 or EV-xxx
	Discoteca        string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`            // e.g., "DataClub"
	NombreEvento     string                 `protobuf:"bytes,3,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Categoria        string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Comuna           string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio           int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock            int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	FechaEvento      string                 `protobuf:"bytes,8,opt,name=fecha_evento,json=fechaEvento,proto3" json:"fecha_evento,omitempty"`
	FechaPublicacion string                 `protobuf:"bytes,9,opt,name=fecha_publicacion,json=fechaPublicacion,proto3" json:"fecha_publicacion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Event) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Event) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Event) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Event) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Event) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Event) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *Event) GetFechaPublicacion() string {
	if x != nil {
		return x.FechaPublicacion
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MedioPago     string                 `protobuf:"bytes,3,opt,name=medio_pago,json=medioPago,proto3" json:"medio_pago,omitempty"` // "debito" or "credito"
	Monto         int32                  `protobuf:"varint,4,opt,name=monto,proto3" json:"monto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *BuyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BuyRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BuyRequest) GetMedioPago() string {
	if x != nil {
		return x.MedioPago
	}
	return ""
}

func (x *BuyRequest) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *BuyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *BuyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TicketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Discoteca     string                 `protobuf:"bytes,4,opt,name=discoteca,proto3" json:"discoteca,omitempty"`
	NombreEvento  string                 `protobuf:"bytes,5,opt,name=nombre_evento,json=nombreEvento,proto3" json:"nombre_evento,omitempty"`
	Precio        int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	FechaCompra   string                 `protobuf:"bytes,7,opt,name=fecha_compra,json=fechaCompra,proto3" json:"fecha_compra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketInfo) Reset() {
	*x = TicketInfo{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInfo) ProtoMessage() {}

func (x *TicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInfo.ProtoReflect.Descriptor instead.
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *TicketInfo) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TicketInfo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketInfo) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *TicketInfo) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *TicketInfo) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *TicketInfo) GetFechaCompra() string {
	if x != nil {
		return x.FechaCompra
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketInfo          `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *HistoryResponse) GetTickets() []*TicketInfo {
	if x != nil {
		return x.Tickets
	}
	return nil
}

// DB Node Service and Messages
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // e.g., "event:<id>" or "ticket:<id>"
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in nanoseconds for LWW consistency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *WriteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *ReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadResponse) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *ReadResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *SyncRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type DBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueJson     string                 `protobuf:"bytes,1,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBEntry) Reset() {
	*x = DBEntry{}
	mi := &file_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEntry) ProtoMessage() {}

func (x *DBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEntry.ProtoReflect.Descriptor instead.
func (*DBEntry) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *DBEntry) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *DBEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbData        map[string]*DBEntry    `protobuf:"bytes,1,rep,name=db_data,json=dbData,proto3" json:"db_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *SyncResponse) GetDbData() map[string]*DBEntry {
	if x != nil {
		return x.DbData
	}
	return nil
}

// USM Bank Service
type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // "debito" or "credito"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *PaymentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_proto_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{19}
}

func (x *PaymentResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"|\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x122\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x11.proto.EntityTypeR\n" +
	"entityType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12#\n" +
	"\rnombre_evento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12!\n" +
	"\ffecha_evento\x18\b \x01(\tR\vfechaEvento\x12+\n" +
	"\x11fecha_publicacion\x18\t \x01(\tR\x10fechaPublicacion\"E\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetEventsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"9\n" +
	"\x11GetEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.proto.EventR\x06events\"y\n" +
	"\n" +
	"BuyRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"medio_pago\x18\x03 \x01(\tR\tmedioPago\x12\x14\n" +
	"\x05monto\x18\x04 \x01(\x05R\x05monto\"^\n" +
	"\vBuyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"-\n" +
	"\x0eHistoryRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xdf\x01\n" +
	"\n" +
	"TicketInfo\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1c\n" +
	"\tdiscoteca\x18\x04 \x01(\tR\tdiscoteca\x12#\n" +
	"\rnombre_evento\x18\x05 \x01(\tR\fnombreEvento\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12!\n" +
	"\ffecha_compra\x18\a \x01(\tR\vfechaCompra\">\n" +
	"\x0fHistoryResponse\x12+\n" +
	"\atickets\x18\x01 \x03(\v2\x11.proto.TicketInfoR\atickets\"]\n" +
	"\fWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"C\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x7f\n" +
	"\fReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"9\n" +
	"\vSyncRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\"F\n" +
	"\aDBEntry\x12\x1d\n" +
	"\n" +
	"value_json\x18\x01 \x01(\tR\tvalueJson\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x93\x01\n" +
	"\fSyncResponse\x128\n" +
	"\adb_data\x18\x01 \x03(\v2\x1f.proto.SyncResponse.DbDataEntryR\x06dbData\x1aI\n" +
	"\vDbDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.proto.DBEntryR\x05value:\x028\x01\"]\n" +
	"\x0ePaymentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"G\n" +
	"\x0fPaymentResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*K\n" +
	"\n" +
	"EntityType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bPRODUCER\x10\x01\x12\n" +
	"\n" +
	"\x06DBNODE\x10\x02\x12\f\n" +
	"\bCONSUMER\x10\x03\x12\b\n" +
	"\x04BANK\x10\x042\xc1\x02\n" +
	"\rBrokerService\x12A\n" +
	"\x0eRegisterEntity\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\x124\n" +
	"\fPublishEvent\x12\f.proto.Event\x1a\x16.proto.PublishResponse\x12>\n" +
	"\tGetEvents\x12\x17.proto.GetEventsRequest\x1a\x18.proto.GetEventsResponse\x122\n" +
	"\tBuyTicket\x12\x11.proto.BuyRequest\x1a\x12.proto.BuyResponse\x12C\n" +
	"\x12GetPurchaseHistory\x12\x15.proto.HistoryRequest\x1a\x16.proto.HistoryResponse2\xb1\x01\n" +
	"\rDBNodeService\x126\n" +
	"\tWriteData\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\x123\n" +
	"\bReadData\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\x123\n" +
	"\bSyncNode\x12\x12.proto.SyncRequest\x1a\x13.proto.SyncResponse2O\n" +
	"\fBancoService\x12?\n" +
	"\x0eProcessPayment\x12\x15.proto.PaymentRequest\x1a\x16.proto.PaymentResponseB\fZ\n" +
	"lab2/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_service_proto_goTypes = []any{
	(EntityType)(0),           // 0: proto.EntityType
	(*RegisterRequest)(nil),   // 1: proto.RegisterRequest
	(*RegisterResponse)(nil),  // 2: proto.RegisterResponse
	(*Event)(nil),             // 3: proto.Event
	(*PublishResponse)(nil),   // 4: proto.PublishResponse
	(*GetEventsRequest)(nil),  // 5: proto.GetEventsRequest
	(*GetEventsResponse)(nil), // 6: proto.GetEventsResponse
	(*BuyRequest)(nil),        // 7: proto.BuyRequest
	(*BuyResponse)(nil),       // 8: proto.BuyResponse
	(*HistoryRequest)(nil),    // 9: proto.HistoryRequest
	(*TicketInfo)(nil),        // 10: proto.TicketInfo
	(*HistoryResponse)(nil),   // 11: proto.HistoryResponse
	(*WriteRequest)(nil),      // 12: proto.WriteRequest
	(*WriteResponse)(nil),     // 13: proto.WriteResponse
	(*ReadRequest)(nil),       // 14: proto.ReadRequest
	(*ReadResponse)(nil),      // 15: proto.ReadResponse
	(*SyncRequest)(nil),       // 16: proto.SyncRequest
	(*DBEntry)(nil),           // 17: proto.DBEntry
	(*SyncResponse)(nil),      // 18: proto.SyncResponse
	(*PaymentRequest)(nil),    // 19: proto.PaymentRequest
	(*PaymentResponse)(nil),   // 20: proto.PaymentResponse
	nil,                       // 21: proto.SyncResponse.DbDataEntry
}
var file_proto_service_proto_depIdxs = []int32{
	0,  // 0: proto.RegisterRequest.entity_type:type_name -> proto.EntityType
	3,  // 1: proto.GetEventsResponse.events:type_name -> proto.Event
	10, // 2: proto.HistoryResponse.tickets:type_name -> proto.TicketInfo
	21, // 3: proto.SyncResponse.db_data:type_name -> proto.SyncResponse.DbDataEntry
	17, // 4: proto.SyncResponse.DbDataEntry.value:type_name -> proto.DBEntry
	1,  // 5: proto.BrokerService.RegisterEntity:input_type -> proto.RegisterRequest
	3,  // 6: proto.BrokerService.PublishEvent:input_type -> proto.Event
	5,  // 7: proto.BrokerService.GetEvents:input_type -> proto.GetEventsRequest
	7,  // 8: proto.BrokerService.BuyTicket:input_type -> proto.BuyRequest
	9,  // 9: proto.BrokerService.GetPurchaseHistory:input_type -> proto.HistoryRequest
	12, // 10: proto.DBNodeService.WriteData:input_type -> proto.WriteRequest
	14, // 11: proto.DBNodeService.ReadData:input_type -> proto.ReadRequest
	16, // 12: proto.DBNodeService.SyncNode:input_type -> proto.SyncRequest
	19, // 13: proto.BancoService.ProcessPayment:input_type -> proto.PaymentRequest
	2,  // 14: proto.BrokerService.RegisterEntity:output_type -> proto.RegisterResponse
	4,  // 15: proto.BrokerService.PublishEvent:output_type -> proto.PublishResponse
	6,  // 16: proto.BrokerService.GetEvents:output_type -> proto.GetEventsResponse
	8,  // 17: proto.BrokerService.BuyTicket:output_type -> proto.BuyResponse
	11, // 18: proto.BrokerService.GetPurchaseHistory:output_type -> proto.HistoryResponse
	13, // 19: proto.DBNodeService.WriteData:output_type -> proto.WriteResponse
	15, // 20: proto.DBNodeService.ReadData:output_type -> proto.ReadResponse
	18, // 21: proto.DBNodeService.SyncNode:output_type -> proto.SyncResponse
	20, // 22: proto.BancoService.ProcessPayment:output_type -> proto.PaymentResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
