// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_RegisterEntity_FullMethodName     = "/proto.BrokerService/RegisterEntity"
	BrokerService_PublishEvent_FullMethodName       = "/proto.BrokerService/PublishEvent"
	BrokerService_GetEvents_FullMethodName          = "/proto.BrokerService/GetEvents"
	BrokerService_BuyTicket_FullMethodName          = "/proto.BrokerService/BuyTicket"
	BrokerService_GetPurchaseHistory_FullMethodName = "/proto.BrokerService/GetPurchaseHistory"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Broker Service
type BrokerServiceClient interface {
	RegisterEntity(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	PublishEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*PublishResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	BuyTicket(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error)
	GetPurchaseHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) RegisterEntity(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, BrokerService_RegisterEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) PublishEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, BrokerService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, BrokerService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) BuyTicket(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyResponse)
	err := c.cc.Invoke(ctx, BrokerService_BuyTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) GetPurchaseHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, BrokerService_GetPurchaseHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
//
// Broker Service
type BrokerServiceServer interface {
	RegisterEntity(context.Context, *RegisterRequest) (*RegisterResponse, error)
	PublishEvent(context.Context, *Event) (*PublishResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	BuyTicket(context.Context, *BuyRequest) (*BuyResponse, error)
	GetPurchaseHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) RegisterEntity(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEntity not implemented")
}
func (UnimplementedBrokerServiceServer) PublishEvent(context.Context, *Event) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedBrokerServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedBrokerServiceServer) BuyTicket(context.Context, *BuyRequest) (*BuyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyTicket not implemented")
}
func (UnimplementedBrokerServiceServer) GetPurchaseHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPurchaseHistory not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_RegisterEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RegisterEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RegisterEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).RegisterEntity(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).PublishEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_BuyTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).BuyTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_BuyTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).BuyTicket(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_GetPurchaseHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).GetPurchaseHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_GetPurchaseHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).GetPurchaseHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEntity",
			Handler:    _BrokerService_RegisterEntity_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _BrokerService_PublishEvent_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _BrokerService_GetEvents_Handler,
		},
		{
			MethodName: "BuyTicket",
			Handler:    _BrokerService_BuyTicket_Handler,
		},
		{
			MethodName: "GetPurchaseHistory",
			Handler:    _BrokerService_GetPurchaseHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	DBNodeService_WriteData_FullMethodName = "/proto.DBNodeService/WriteData"
	DBNodeService_ReadData_FullMethodName  = "/proto.DBNodeService/ReadData"
	DBNodeService_SyncNode_FullMethodName  = "/proto.DBNodeService/SyncNode"
)

// DBNodeServiceClient is the client API for DBNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBNodeServiceClient interface {
	WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	SyncNode(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type dBNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDBNodeServiceClient(cc grpc.ClientConnInterface) DBNodeServiceClient {
	return &dBNodeServiceClient{cc}
}

func (c *dBNodeServiceClient) WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, DBNodeService_WriteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeServiceClient) ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DBNodeService_ReadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBNodeServiceClient) SyncNode(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, DBNodeService_SyncNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBNodeServiceServer is the server API for DBNodeService service.
// All implementations must embed UnimplementedDBNodeServiceServer
// for forward compatibility.
type DBNodeServiceServer interface {
	WriteData(context.Context, *WriteRequest) (*WriteResponse, error)
	ReadData(context.Context, *ReadRequest) (*ReadResponse, error)
	SyncNode(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedDBNodeServiceServer()
}

// UnimplementedDBNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBNodeServiceServer struct{}

func (UnimplementedDBNodeServiceServer) WriteData(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteData not implemented")
}
func (UnimplementedDBNodeServiceServer) ReadData(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedDBNodeServiceServer) SyncNode(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncNode not implemented")
}
func (UnimplementedDBNodeServiceServer) mustEmbedUnimplementedDBNodeServiceServer() {}
func (UnimplementedDBNodeServiceServer) testEmbeddedByValue()                       {}

// UnsafeDBNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBNodeServiceServer will
// result in compilation errors.
type UnsafeDBNodeServiceServer interface {
	mustEmbedUnimplementedDBNodeServiceServer()
}

func RegisterDBNodeServiceServer(s grpc.ServiceRegistrar, srv DBNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedDBNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBNodeService_ServiceDesc, srv)
}

func _DBNodeService_WriteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServiceServer).WriteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNodeService_WriteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServiceServer).WriteData(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNodeService_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServiceServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNodeService_ReadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServiceServer).ReadData(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBNodeService_SyncNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBNodeServiceServer).SyncNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBNodeService_SyncNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBNodeServiceServer).SyncNode(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBNodeService_ServiceDesc is the grpc.ServiceDesc for DBNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DBNodeService",
	HandlerType: (*DBNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteData",
			Handler:    _DBNodeService_WriteData_Handler,
		},
		{
			MethodName: "ReadData",
			Handler:    _DBNodeService_ReadData_Handler,
		},
		{
			MethodName: "SyncNode",
			Handler:    _DBNodeService_SyncNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

const (
	BancoService_ProcessPayment_FullMethodName = "/proto.BancoService/ProcessPayment"
)

// BancoServiceClient is the client API for BancoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BancoServiceClient interface {
	ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type bancoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBancoServiceClient(cc grpc.ClientConnInterface) BancoServiceClient {
	return &bancoServiceClient{cc}
}

func (c *bancoServiceClient) ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, BancoService_ProcessPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BancoServiceServer is the server API for BancoService service.
// All implementations must embed UnimplementedBancoServiceServer
// for forward compatibility.
type BancoServiceServer interface {
	ProcessPayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedBancoServiceServer()
}

// UnimplementedBancoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBancoServiceServer struct{}

func (UnimplementedBancoServiceServer) ProcessPayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedBancoServiceServer) mustEmbedUnimplementedBancoServiceServer() {}
func (UnimplementedBancoServiceServer) testEmbeddedByValue()                      {}

// UnsafeBancoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BancoServiceServer will
// result in compilation errors.
type UnsafeBancoServiceServer interface {
	mustEmbedUnimplementedBancoServiceServer()
}

func RegisterBancoServiceServer(s grpc.ServiceRegistrar, srv BancoServiceServer) {
	// If the following call panics, it indicates UnimplementedBancoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BancoService_ServiceDesc, srv)
}

func _BancoService_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BancoServiceServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BancoService_ProcessPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BancoServiceServer).ProcessPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BancoService_ServiceDesc is the grpc.ServiceDesc for BancoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BancoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BancoService",
	HandlerType: (*BancoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPayment",
			Handler:    _BancoService_ProcessPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
